clear; clc;

load('ElementXS.mat')
load('source_energy_vec.mat')

Rayleigh = sum(Rayleigh.*repmat(source_energy_vec(1:149)',1,28));
Compton = sum(Compton.*repmat(source_energy_vec(1:149)',1,28));
Photon = sum(Photon.*repmat(source_energy_vec(1:149)',1,28));

ind_vec = [1,23,24,25,6,12,22];
figure;
subplot(2,1,2);
loglog(Rayleigh(ind_vec),Compton(ind_vec),'ro','MarkerFaceColor','r')
% xlim([0,8e-24]);
% ylim([0,11e-24]);
% xlabel('Rayleigh');
% ylabel('Compton');
% set(gca,'Visible','off')
% axes('Position',get(gca,'Position'),...
%  'XAxisLocation','bottom',...
%  'YAxisLocation','left',...
%  'Color','none',...
%  'XTickLabel',get(gca,'XTickLabel'),...
%  'YTickLabel',get(gca,'YTickLabel'),...
%  'XColor','k','YColor','k',...
%  'LineWidth',1,...
%  'TickDir','out');
set(gca,'FontSize',18);
% xt = xticks;
% xticks(xt(1:2:end));
subplot(2,1,1);
loglog(Rayleigh(ind_vec)+Compton(ind_vec),Photon(ind_vec),'ro','MarkerFaceColor','r')
% xlim([0,2e-23]);
% ylim([0,10e-23]);
% xlabel('Scatter');
% ylabel('Absoption');
% set(gca,'Visible','off')
% axes('Position',get(gca,'Position'),...
%  'XAxisLocation','bottom',...
%  'YAxisLocation','left',...
%  'Color','none',...
%  'XTickLabel',get(gca,'XTickLabel'),...
%  'YTickLabel',get(gca,'YTickLabel'),...
%  'XColor','k','YColor','k',...
%  'LineWidth',1,...
%  'TickDir','out');
set(gca,'FontSize',18);